'use client';

import { Inter } from 'next/font/google';

import type { Metadata } from 'next';

import './globals.css';
import { Auth0Provider } from '@auth0/auth0-react';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Auth0Provider
          domain="dev-lubuvw0qul5rra7p.us.auth0.com"
          clientId="5D1s5pRVEVwG6xP2GWfA5wrW3x6HAj6M"
          authorizationParams={{
            redirect_uri: window.location.origin,
          }}
        >
          {children}
        </Auth0Provider>
      </body>
    </html>
  );
}
