name: Deploy S3 and CloudFront
on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/deploy.yaml"

env:
  NODE_VERSION: "18"
  AWS_REGION: "ap-northeast-1"
  IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.12.1

      - run: pnpm install
        working-directory: ./frontend

      - run: pnpm build
        working-directory: ./frontend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.IAM_ROLE_ARN}}

      - name: Upload files to S3 and Clear CF cache
        run: |
          aws s3 sync --exact-timestamps --delete ./frontend/out s3://${{ env.AWS_BUCKET_NAME }}/
          aws cloudfront create-invalidation --distribution-id ${{ env.CF_DISTRIBUTION_ID }} --paths "/*"
